version: '3'

networks:
   front:
   back:

services:
   nginx_front:
      image: nginx
      restart: always  
      container_name: bayne_fe_server  
      ports:
         - "8088:80"
      volumes: #like symlink
         - ./bayne-frontend/src:/var/www/html
         - ./nginx/bayne-frontend.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - php_front
      networks:
         - front

   nginx_back:
      image: nginx
      restart: always  
      container_name: bayne_be_server   
      ports:
         - "8089:80"
      volumes: #like symlink
         - ./bayne-backend/src:/var/www/html
         - ./nginx/bayne-backend.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - php_back
         - mysql
      networks:
         - back

   mysql:
      image: mysql:latest
      command:
            - "--default-authentication-plugin=mysql_native_password"
      container_name: bayne_mysql
      restart: unless-stopped #this will restart if the mysql-container stops
      tty: true #enables the shell interface that we need to interact with mysql container
      volumes:
         - ./mysql:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: bayne_db
         MYSQL_USER: nomariano
         MYSQL_PASSWORD: p@$$w0rDmariano
      ports:
         - "4306:3306" 
      networks:
         - back

   php_front:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: bayne_php_front
      volumes:
         - ./bayne-frontend/src:/var/www/html
      ports:
         - "9000:9000"
      networks:
         - front

   php_back:
      build:
         context: .
         dockerfile: Dockerfile
      container_name: bayne_php_back
      volumes:
         - ./bayne-backend/src:/var/www/html
      ports:
         - "9090:9000"
      networks:
         - back

   redis:
      build:
         context: ./redis
      image: redis:latest
      container_name: bayne_redis
      ports:
         - "6378:6379"